//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doluuniem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.ThanhToan = new HashSet<ThanhToan>();
        }
    
        public int MaDonHang { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThai { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<ThanhToan> ThanhToan { get; set; }
        public string YeuCauDacBiet { get; internal set; }
        public string MaGiamGia { get; internal set; }
    }
}
