//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doluuniem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.DanhGia = new HashSet<DanhGia>();
            this.GioHang = new HashSet<GioHang>();
            this.ChiTietSanPham = new HashSet<ChiTietSanPham>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> MaLoaiSanPham { get; set; }
        public string MauSac { get; set; }
        public string KichThuoc { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        public virtual ICollection<GioHang> GioHang { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual ICollection<ChiTietSanPham> ChiTietSanPham { get; set; }
    }
}
